# =============================================================================
# Copyright (c) 2025, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
# =============================================================================


function(add_copy_fatbins_command target_name)
  get_target_property(dest ${target_name} RUNTIME_OUTPUT_DIRECTORY)
  add_custom_target(copy_${target_name} ALL
    DEPENDS ${target_name}
    COMMAND ${CMAKE_COMMAND} -DDEST=${dest} "-DFATBINS=$<TARGET_OBJECTS:${target_name}>" -P ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/detail/copy_fatbins.cmake
    COMMENT "copying fatbins generated by ${target_name}"
    VERBATIM)

  # issue this won't trigger unless we build it manually since it has no consumers
  # :(
endfunction()

